# PROYECTO FINAL 
# METODOS MATEMÁTICOS PARA EL ANÁLISIS DE LOS DATOS 

##**MODELO INPUT-OUTPUT (LEONTIEF)**

> UNIVERSIDAD DE GUADALAJARA      
> MAESTRIA EN CIENCIA DE LOS DATOS     


**220981202 PEDRO MARTÍNEZ AYALA**     
**393813438 AFRA JULIETA JULIETA LOMELI ÁVILA**    
**220481261 MÓNICA ALONSO SORIA**                    
    
09.11.2020

##**ACERCA DEL MODELO INSUMO - PRODUCTO (LEONTIEF)**

----

En Agosto de 1936 Wassily Leontief publicó "Quantitative Input and Output relations in the Economy System of the United States"  en *The Review of Economic Statistics*, teoría por la cual sería galardonado con el Premio Nobel de Economía en 1973.

La versión "abierta" de su modelo tiene como propósito determinar la producción bruta por sector para satisfacer la demanda de un país entero. 

**VARIABLES DE ENTRADA**

* S1, S2, S3,..., Sn son las industrias o sectores 
* $q_{ij}$  es número de unidades producidas por la industria $S_j$  para la industria $S_i$   
*$d$ es la demanda final o demanda externa de productos (lo que consume el sector no productivo)
* X1,X2,X3,...Xn es la producción total de cada industria  S1, S2, S3,..., Sn

**FÓRMULAS**   
En lugar de $q_{ij}$  el modelo necesita $a_{ij}$  , el número de unidades producidas por la industria  $S_j$ necesarias para producir una unidad en la industria $S_i$ . Construimos entonces la matriz de consumo total.


\begin{equation}
A =
\begin{pmatrix}
a_{11}  & \cdots & a_{1n}\\
\vdots & & \vdots\\
a_{n1}  & \cdots & a_{nn}
\end{pmatrix}
\end{equation}

Para estimar el modelo abierto de Leontief se requiere que  A y d (vector de demanda externa)  sean diferentes de cero. 

\begin{equation}
A {\quad} y {\quad} d  \neq
\begin{pmatrix}
0  \\
\vdots \\
 0\\
\end{pmatrix}
\end{equation}


Leontief plantea entonces, un sistema de ecuaciones lineales equivalentes a la ecuación matricial: 

\begin{equation}
X = AX  + d 
\end{equation}

Se puede transformar esta ecuación de la siguente manera: 

\begin{equation}
I_nX - AX    = d 
\end{equation}
\begin{equation}   
(I_nX - A) X = d       
\end{equation}
\begin{equation}   
X = (I_nX - A)^{-1}d       
\end{equation}   


Si la inversa de la matriz $(I_nX - A)$ existe entonces $(I_nX - A)^{-1}d$ es llamada la inversa de Leontief. 







##**ACERCA DEL SET DE DATOS**


**MATRIZ INSUMO PRODUCTO (BASE 2013)**

La Matriz Insumo-Producto consiste en un conjunto de cuadros que reflejan las relaciones económicas que se llevan a cabo entre los diferentes sectores y agentes en todas las fases del ciclo económico (producción, comercialización, consumo y acumulación) y representa un instrumento de planeación y toma de decisiones para políticas económicas. A través de su uso, se puede responder a múltiples interrogantes sobre las necesidades e impactos en los niveles de producción, insumos, maquinaria y equipo, entre otras, de los diversos sectores económicos.


*   Fuente de información : [INEGI(2013)](https://www.inegi.org.mx/programas/mip/2013/#Herramientas)
*   Archivo  : mip_t_pb_pxp__1_22_45_109_133
*   Titulo original : Matriz simétrica de insumo producto. Produto por producto / Economía total / Origen doméstico e importado / Sector SCIAN / Millones de pesos a precios básicos
* Nota : el valor agregado se tomó del valor agregado bruto 




In [ ]:
# Importar bibliotecas a utilizar 

import pandas as pd 
import matplotlib as plt
import numpy as np 
import seaborn as sns 

In [ ]:
# Cargar dataset (está almacenado en google drive )
data = pd.read_excel("/content/drive/My Drive/Classroom/METODOS MATEMATICOS PARA EL ANALISIS DE DATOS CUCEA/MIP 2013.xlsx") 
data.head()

Unnamed: 0  ...  Producto Total 
0                                                NaN  ...              nan
1  11 - Agricultura, cría y explotación de animal...  ...          815,356
2                                       21 - Minería  ...        1,470,392
3  22 - Generación, transmisión y distribución de...  ...          455,491
4                                  23 - Construcción  ...        2,094,547

[5 rows x 23 columns]

In [ ]:
#EDA 
data = data.drop(data.index[0])
data = data.set_index(['Unnamed: 0'])
data.head()
data = data.replace(np.nan,0)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, 11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza to Insumo Total 
Data columns (total 22 columns):
 #   Column                                                                                                                           Non-Null Count  Dtype  
---  ------                                                                                                                           --------------  -----  
 0   11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza                                         22 non-null     float64
 1   21 - Minería                                                                                                                     22 non-null     float64
 2   22 - Generación, transmisión y distribución de energía eléctrica, suministro de agua y de gas por ductos al consumidor final     22 non-null     float64
 3   23 - Cons

In [ ]:
data.tail()

11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza  ...  Producto Total 
Unnamed: 0                                                                                                                                    ...                 
72 - Servicios de alojamiento temporal y de pre...                                                135                                         ...          526,216
81 - Otros servicios excepto actividades gubern...                                                777                                         ...          471,004
93 - Actividades legislativas, gubernamentales,...                                                  0                                         ...          952,005
Valor agregado                                                                                510,906                                         ...       64,077,384
Insumo Total                                                                                  814,874                                         ...       91,720,033

[5 rows x 22 columns]

####**PROCEDIMIENTO**

In [ ]:
# Matriz de Coeficientes (A)
# Calcular los requerimientos por cada dólar de producción 

matriz_coeficientes = data.loc[:,'11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza':].div(data.iloc[-1]['11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza':])
matriz_coeficientes.tail(1) # Comprobar que la división se efectó de forma correcta 


11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza  ...  Producto Total 
Unnamed: 0                                                                                               ...                 
Insumo Total                                                   1                                         ...                1

[1 rows x 22 columns]

In [ ]:
# Impacto COVID  : sujeto a consideración de un experto (ingresar un shok % en la demanda)

shock_porcentual = 1 #expresar en decimales (e.g. -.10)
data['11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza'] = data['11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza'] * shock_porcentual

In [ ]:
# Quitar : valor aregado, insumo total, demanda final y producto total porque NO van en la matriz de coeficientes 
matriz_coeficientes = matriz_coeficientes.drop(['Demanda Final '],axis = 1)
matriz_coeficientes = matriz_coeficientes.drop(['Producto Total '] ,axis = 1) 
matriz_coeficientes = matriz_coeficientes.drop([matriz_coeficientes.index[-2] , matriz_coeficientes.index[-1]])  #Elimnar valor agregado y demanda final (son las últimas 2 filas)

In [ ]:
#Estructura de la tabla 
rows = matriz_coeficientes.shape[0] 
cols = matriz_coeficientes.shape[1] 
print("Rows: " + str(rows)) 
print("Columns: " + str(cols)) 

matriz_coeficientes.tail()

Rows: 20
Columns: 20


11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza  ...  93 - Actividades legislativas, gubernamentales, de impartición de justicia y de organismos internacionales y extraterritoriales
Unnamed: 0                                                                                                                                    ...                                                                                                                                 
62 - Servicios de salud y de asistencia social                                                      0                                         ...                                                  0                                                                              
71 - Servicios de esparcimiento culturales y de...                                                  0                                         ...                                                  0                                                                              
72 - Servicios de alojamiento temporal y de pre...                                                  0                                         ...                                                  0                                                                              
81 - Otros servicios excepto actividades gubern...                                                  0                                         ...                                                  0                                                                              
93 - Actividades legislativas, gubernamentales,...                                                  0                                         ...                                                  0                                                                              

[5 rows x 20 columns]

In [ ]:
# Matriz de coeficientes 
A =  np.matrix(matriz_coeficientes)
A

matrix([[9.13481583e-02, 6.08717269e-07, 0.00000000e+00, 7.04856094e-04,
         5.24665116e-02, 1.94168911e-07, 7.86176324e-07, 1.27108925e-06,
         3.53687297e-06, 0.00000000e+00, 2.35360379e-06, 1.74762898e-06,
         7.25854227e-07, 2.50482702e-07, 5.65397167e-04, 1.63915588e-04,
         6.30555573e-05, 1.04127210e-02, 2.35344128e-06, 2.24223745e-05],
        [1.29514493e-03, 5.46700787e-03, 2.88942776e-02, 3.40857429e-02,
         7.11346303e-02, 3.91388152e-05, 6.98680707e-05, 1.05758352e-04,
         2.94759396e-04, 0.00000000e+00, 1.95955919e-04, 1.51416248e-04,
         6.08911046e-05, 2.99960402e-05, 2.86287425e-05, 1.14342388e-04,
         1.49545757e-04, 2.79719852e-05, 1.97089046e-04, 5.26154057e-05],
        [1.65137962e-02, 1.12951771e-02, 4.98555210e-02, 5.91135883e-03,
         1.59468493e-02, 5.12654592e-03, 1.79952539e-02, 4.12178491e-03,
         6.39476079e-03, 3.27446197e-03, 3.44700993e-03, 1.25597145e-02,
         1.57489465e-02, 7.90907971e-03, 1.548559

In [ ]:
# Matriz de identidad (I)
I = np.identity(rows)
#matriz_identidad = pd.DataFrame(matriz_identidad)}
I = np.matrix(I)
I

matrix([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0

In [ ]:
# Matriz I-A 
matriz_diferencia = I - A 
matriz_diferencia


matrix([[ 9.08651842e-01, -6.08717269e-07,  0.00000000e+00,
         -7.04856094e-04, -5.24665116e-02, -1.94168911e-07,
         -7.86176324e-07, -1.27108925e-06, -3.53687297e-06,
          0.00000000e+00, -2.35360379e-06, -1.74762898e-06,
         -7.25854227e-07, -2.50482702e-07, -5.65397167e-04,
         -1.63915588e-04, -6.30555573e-05, -1.04127210e-02,
         -2.35344128e-06, -2.24223745e-05],
        [-1.29514493e-03,  9.94532992e-01, -2.88942776e-02,
         -3.40857429e-02, -7.11346303e-02, -3.91388152e-05,
         -6.98680707e-05, -1.05758352e-04, -2.94759396e-04,
          0.00000000e+00, -1.95955919e-04, -1.51416248e-04,
         -6.08911046e-05, -2.99960402e-05, -2.86287425e-05,
         -1.14342388e-04, -1.49545757e-04, -2.79719852e-05,
         -1.97089046e-04, -5.26154057e-05],
        [-1.65137962e-02, -1.12951771e-02,  9.50144479e-01,
         -5.91135883e-03, -1.59468493e-02, -5.12654592e-03,
         -1.79952539e-02, -4.12178491e-03, -6.39476079e-03,
         -3.

In [ ]:
# Inversa de la matriz (I-A)
from numpy.linalg import inv
matriz_inversa  = np.linalg.inv(matriz_diferencia)
matriz_inversa

matrix([[1.12579983e+00, 1.41399111e-02, 3.83565753e-02, 7.34433489e-02,
         1.12325170e-01, 7.95729546e-03, 7.87083331e-03, 3.09418693e-02,
         1.93519635e-02, 5.34665871e-03, 2.61512275e-03, 9.50282133e-03,
         1.59248176e-02, 7.21504820e-03, 5.43701896e-03, 2.16478158e-02,
         1.28629268e-02, 3.25047472e-02, 1.79070082e-02, 1.01999555e-02],
        [3.36447868e-02, 1.02387907e+00, 7.90969363e-02, 1.31339740e-01,
         1.40557952e-01, 1.02505493e-02, 1.05612741e-02, 3.89997101e-02,
         2.47354504e-02, 7.00084294e-03, 3.72765326e-03, 1.25552071e-02,
         2.06278687e-02, 9.35564342e-03, 6.71984663e-03, 2.77602624e-02,
         1.70942596e-02, 2.72757705e-02, 2.30879240e-02, 1.34660968e-02],
        [2.86232704e-02, 1.79520304e-02, 1.06715311e+00, 3.65737825e-02,
         3.91663591e-02, 9.67139024e-03, 2.28136020e-02, 1.65996252e-02,
         1.61341136e-02, 8.67214304e-03, 5.07956362e-03, 1.84910864e-02,
         2.45328441e-02, 1.18630582e-02, 1.865627

In [ ]:
# Matriz de la demanda final (d)
demanda_final = data['Demanda Final ']
demanda_final = demanda_final.drop([demanda_final.index[-2] , demanda_final.index[-1]]) 
demanda_final
d = np.matrix(demanda_final)
d

matrix([[2.28886127e+05, 7.31156027e+05, 1.18430180e+05, 1.88912337e+06,
         3.31434342e+06, 6.35843675e+05, 1.57473327e+06, 1.30692864e+06,
         3.19135741e+05, 5.80860078e+05, 1.70622698e+06, 3.52182930e+04,
         2.42705000e+02, 4.37671200e+04, 7.43086729e+05, 5.77877290e+05,
         1.07014724e+05, 4.40053757e+05, 3.48650261e+05, 9.50501249e+05]])

In [ ]:
# Matriz Leontief
matriz_leontief = d * matriz_inversa 
matriz_leontief 

matrix([[1861994.19997292, 1665414.64910056, 2572396.89991108,
         6950301.98375057, 6825892.88048198, 1207060.56803722,
         2140927.83918798, 3317071.37941014, 1671049.9507288 ,
         1079836.43942951, 1924804.26433666,  763491.5352072 ,
         1146463.23955461,  536124.82117318, 1088149.49913941,
         2011940.3904411 , 1058816.98825672, 1838633.24319731,
         1571287.74343674, 1694046.26022522]])

In [ ]:
# Presentar resultados por industria 
resultados = pd.DataFrame(matriz_leontief)  # Convertir en un dataframe
resultados.columns = matriz_coeficientes.columns  # Nombrar las industrias 
resultados = resultados.T  # Invertir la tabla para que se vea el nombre completo de la industria 
resultados.columns = ['Producción por industria (Millones de pesos a precios básicos)']  # Ponerle titulo a la columna
pd.options.display.float_format = '{:,.0f}'.format  # Cambiar el formato de número 
resultados 

Producción por industria (Millones de pesos a precios básicos)
11 - Agricultura, cría y explotación de animale...                                          1,861,994             
21 - Minería                                                                                1,665,415             
22 - Generación, transmisión y distribución de ...                                          2,572,397             
23 - Construcción                                                                           6,950,302             
31-33 - Industrias manufactureras                                                           6,825,893             
43 - Comercio al por mayor                                                                  1,207,061             
46 - Comercio al por menor                                                                  2,140,928             
48-49 - Transportes, correos y almacenamiento                                               3,317,071             
51 - Información en medios masivos                                                          1,671,050             
52 - Servicios financieros y de seguros                                                     1,079,836             
53 - Servicios inmobiliarios y de alquiler de b...                                          1,924,804             
54 - Servicios profesionales, científicos y téc...                                            763,492             
55 - Corporativos                                                                           1,146,463             
56 - Servicios de apoyo a los negocios y manejo...                                            536,125             
61 - Servicios educativos                                                                   1,088,149             
62 - Servicios de salud y de asistencia social                                              2,011,940             
71 - Servicios de esparcimiento culturales y de...                                          1,058,817             
72 - Servicios de alojamiento temporal y de pre...                                          1,838,633             
81 - Otros servicios excepto actividades gubern...                                          1,571,288             
93 - Actividades legislativas, gubernamentales,...                                          1,694,046

### FUENTES CONSULTADAS

[1] Leontief,W. (1936) Quantitative Input and Output Relations in the Economic Systems of the United States, Rev. Econ. Stat. 18, 105.

[2] INEGI (2013) Matriz Insumo- Producto . Tomado de: https://www.inegi.org.mx/contenidos/programas/mip/2013/doc/met_mip.pdf

[3] Lay, D.C.(2012) Álgebra lineal y sus aplicaciones. México: Pearson Educación

[4] Haeussler, F.E, & S.Paul, R.(2003). Matemáticas para la administración y economía .México. Pearson Educación.

